### ISSUE TITLE
Not a virtual screening project

### ISSUE THREAD

**Issue by aravindprasad** [anribras/Android-cast-and-control#2]
Please remove the "virtual screening" from your project. Virtual screening is a computational chemistry term used specifically to refer to screening large number of chemical compounds against a (typically) protein target to identify potential drugs to treat disease conditions.

**Comment by anribras** [comment]
> Please remove the "virtual screening" from your project. Virtual screening is a computational chemistry term used specifically to refer to screening large number of chemical compounds against a (typically) protein target to identify potential drugs to treat disease conditions.

Thanks buddy, I've removed it.
